name = "PhysicsInformedML"
uuid = "ddcc5653-dcaa-48f1-be98-eb2dafe13740"
authors = ["monty <velimir.vesselinov@gmail.com>"]
version = "0.1.0"

[deps]
DocumentFunction = "e1f3b4f0-2dc4-57d3-83f7-d4b7faf3b05b"
Mads = "d6bdc55b-bd94-5012-933c-1f73fc2ee992"
NMFk = "e40cd9e2-a1df-5d90-a1fa-603fdc3dbdd8"
NTFk = "1226e131-0b97-51f8-8a3f-c1798118cd52"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
SVR = "22bb73d7-edb2-5785-ba1e-7d60d6824784"

[compat]
DocumentFunction = "^0"
Mads = "^0.10"
NMFk = "^0.6"
NTFk = "^0.3"
SVR = "^0.7"
julia = "^1.4"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]